
import "./globals.css";

export const metadata = {
  title: "Pupilo",
   description: "Generated by create next app ",
  metadataBase: new URL("https://pupilo-cyan.vercel.app/"),
  openGraph: {
    type: "website",
    title: "Pupilo",
    description:
      "Generated by create next app",
    images: "/assets/meta.webp",
  },
 
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
