export const NAV_DATA_LIST = [
  { title: "Home", link: "/" },
  { title: "Courses", link: "#" },
  { title: "Why Pupilo?", link: "#" },
  { title: "Learn with Pupilo", link: "#" },
  { title: "Blog", link: "#" },
];

export const BRAND_LOGO_DATA_LIST = [
  "/assets/images/svg/layers.svg",
  "/assets/images/svg/sisyphus.svg",
  "/assets/images/svg/capsule.svg",
  "/assets/images/svg/catalog.svg",
  "/assets/images/svg/spherule.svg",
  "/assets/images/svg/luminous.svg",
  "/assets/images/svg/focalpoint.svg",
  "/assets/images/svg/polymath.svg",
  "/assets/images/svg/acmeCrop.svg",
  "/assets/images/svg/segment.svg",
  "/assets/images/svg/featherDev.svg",
  "/assets/images/svg/galileo.svg",
];

export const PUPILO_CURRICULUM_LIST = [
  {
    title: "Coding Fundamental",
    description:
      "Young learners begin their journey with visual tools like ScratchJr and Blockly. Focus on basic logic, sequences, loops, and cause-effect thinking. Students build interactive animations, tell stories through code, and develop foundational logic.",
    buttonText: "Try a Free Lesson",
    learnMoreLink: "#learn-more",
    buttonTheme: "white",
    cardTheme: "purple",
    textColor: "white",
    image: "/assets/images/png/coding-fundamental.png",
    imageWeight: 434,
    rightPosition: 20,
    learnMoreLink: "#learn-more",
  },
  {
    title: "Game Development",
    description:
      "Students deepen their understanding with interactive environments like Roblox Studio and Lua scripting. They start coding games and building interactive worlds, while learning conditionals, functions, and more complex logic.",
    buttonText: "Try a Free Lesson",
    learnMoreLink: "#learn-more",
    buttonTheme: "dark",
    cardTheme: "light-purple",
    textColor: "dark-black",
    image: "/assets/images/png/game-development.png",
    imageWeight: 370,
    rightPosition: 90,
    learnMoreLink: "#learn-more",
  },
  {
    title: "Python Programming",
    description:
      "Learners are introduced to text-based coding via Python. Begin with variables, conditions, and loops. Move into functions, simple data structures. They dive into Python, Web Development, and Data Science. ",
    buttonText: "Try a Free Lesson",
    learnMoreLink: "#learn-more",
    buttonTheme: "white",
    cardTheme: "purple",
    textColor: "white",
    image: "/assets/images/png/python-programming.png",
    imageWeight: 454,
    rightPosition: 90,
    learnMoreLink: "#learn-more",
  },
  {
    title: "App & Web Development",
    description:
      "This advanced track prepares teens for university-level coding and tech careers. Learners master full-stack development and explore complex fields like data analytics, software engineering, and version control. ",
    buttonText: "Try a Free Lesson",
    learnMoreLink: "#learn-more",
    buttonTheme: "dark",
    cardTheme: "yellow",
    textColor: "dark-black",
    image: "/assets/images/png/app-and-web-development.png",
    imageWeight: 304,
    rightPosition: 123,
    learnMoreLink: "#learn-more",
  },
];
export const TECH_JOURNEY_CARDS_LIST = [
  {
    grade: "Grades 2-3",
    title: "Little Explorers",
    description:
      "Young learners begin their journey with visual tools like ScratchJr and Blockly. Focus on basic logic, sequences, loops, and cause-effect thinking. Students build interactive animations, tell stories through code, and develop foundational logic.",
    skills: [
      "Critical thinking",
      "Creativity & imagination",
      "Early programming concepts",
      "Problem Solving",
    ],
    tools: [
      "/assets/images/webp/scratch-jr-tool.webp",
      "/assets/images/webp/blockly-games-tools.webp",
      "/assets/images/webp/lightbot-tools.webp",
    ],
    image: "/assets/images/webp/little-explorers.webp",
    cardTheme: "purple",
    textColor: "white",
    buttonText: "Try a Free Lesson",
    buttonTheme: "white",
    badgeBorder: "white",
    levelTextTheme: "text-purple",
  },
  {
    grade: "Grades 4-6",
    title: "Little Creators",
    description:
      "Students deepen their understanding with interactive environments like Roblox Studio and Lua scripting. They start coding games and building interactive worlds, while learning conditionals, functions, and more complex logic. Introduce teamwork and iteration.",
    skills: [
      "Game development",
      "Project-based learning",
      "Collaborative coding",
      "Story-driven design thinking",
    ],
    tools: [
      "/assets/images/webp/roblox-tools.webp",
      "/assets/images/webp/scratch-jr-tool.webp",
      "/assets/images/webp/tynker-tools.webp",
    ],
    image: "/assets/images/webp/little-creators.webp",
    cardTheme: "light-purple",
    buttonText: "Try a Free Lesson",
    buttonTheme: "dark-black",
    badgeBorder: "dark-black",
    levelTextTheme: "text-light-purple",
  },
  {
    grade: "Grades 6-9",
    title: "Little Programmers",
    description:
      "Learners are introduced to text-based coding via Python. Begin with variables, conditions, and loops. Move into functions, simple data structures. They dive into Python, Web Development, and Data Science. From chatbots to smart assistants, they explore real-world tech applications.",
    skills: [
      "Data analysis",
      "Logical reasoning",
      "Web & app prototyping",
      "Coding for real-world use cases",
    ],
    tools: [
      "/assets/images/webp/replit-tools.webp",
      "/assets/images/webp/jupyterlite-tools.webp",
      "/assets/images/webp/trinket-tools.webp",
    ],
    image: "/assets/images/webp/little-programmers.webp",
    cardTheme: "blue",
    textColor: "white",
    buttonText: "Try a Free Lesson",
    buttonTheme: "white",
    badgeBorder: "white",
    levelTextTheme: "text-blue",
  },
  {
    grade: "Grades 9-12",
    title: "Master Programmers",
    description:
      "Learners build landing pages, mini-apps, and explore tools like Thunkable or MIT App Inventor for mobile apps. High schoolers create full projects—portfolios, e-commerce mockups, and more. Each level builds on the last, and learners can move between tracks based on interest or skill level.",
    skills: [
      "Full-stack programming",
      "Project deployment & testing",
      "Real-world coding confidence",
      "Problem-solving at scale",
    ],
    tools: [
      "/assets/images/webp/chatgpt-tool-logo.webp",
      "/assets/images/webp/flask-tools.webp",
      "/assets/images/webp/firebase-tool.webp",
    ],
    image: "/assets/images/webp/master-programmers.webp",
    cardTheme: "yellow",
    buttonText: "Try a Free Lesson",
    buttonTheme: "dark-black",
    badgeBorder: "dark-black",
    levelTextTheme: "text-yellow",
  },
];
export const ADD_ON_COURSES_LIST = [
  {
    title: "Minecraft 1:1 Coding Course",
    description:
      "In this exciting course, learners will explore coding fundamentals by modifying (modding) the Minecraft world using block-based coding tools like Microsoft MakeCode and Blockly, and progress to Python for advanced learners.",
    buttonText: "Try a Free Lesson",
    learnMoreLink: "#learn-more",
    buttonTheme: "white",
    cardTheme: "purple",
    textColor: "white",
    image: "/assets/images/webp/minecraft-coding-course.webp",
    imageWeight: 309,
    rightPosition: 70,
    learnMoreLink: "#learn-more",
  },
  {
    title: "Fun Coding Math",
    description:
      "This course blends math and logic using Scratch and visual puzzles. Concepts like number patterns, geometry, and measurement come alive through coding mini-projects.",
    buttonText: "Try a Free Lesson",
    learnMoreLink: "#learn-more",
    buttonTheme: "dark",
    cardTheme: "light-purple",
    textColor: "dark-black",
    image: "/assets/images/webp/fun-coding-math.webp",
    imageWeight: 389,
    rightPosition: 61,
    learnMoreLink: "#learn-more",
  },
  {
    title: "Game Development & Storytelling",
    description:
      "Learner will build a game where Shaka Zulu Saves a Village using Scratch and Roblox Studio. They will learn events, characters, scoring systems, and storytelling.",
    buttonText: "Try a Free Lesson",
    learnMoreLink: "#learn-more",
    buttonTheme: "white",
    cardTheme: "purple",
    textColor: "white",
    image: "/assets/images/webp/game-development-and-storytelling.webp",
    imageWeight: 452,
    rightPosition: 40,
    learnMoreLink: "#learn-more",
  },
  {
    title: "Artificial Intelligence",
    description:
      "Learners start with AI basics: pattern recognition, chatbots, and machine learning concepts using Teachable Machine or block-based AI tools. Advance to ethical AI, image recognition, and Python-based AI in high school.",
    buttonText: "Try a Free Lesson",
    learnMoreLink: "#learn-more",
    buttonTheme: "dark",
    cardTheme: "yellow",
    textColor: "dark-black",
    image: "/assets/images/webp/artificial-intelligence.webp",
    imageWeight: 289,
    rightPosition: 92,
    learnMoreLink: "#learn-more",
  },
];
